#!/usr/bin/env python3
"""Build the board's die asset: assets/dice/models/die.glb, plus the face atlas it bakes in.

WHY THIS IS BUILT RATHER THAN RECONSTRUCTED
-------------------------------------------
Every other 3D asset here comes back from Scenario's image-to-3D step. A die can't. Image-to-3D
sees one render, so it sees at most three faces; the other three are invented, and the pip counts
it invents are wrong roughly as often as not. Worse, nothing in that pipeline knows that a die's
faces are not independent — opposite faces must sum to 7, and the three faces around a corner
must run counter-clockwise for a right-handed die. A generator has no reason to honour either.

So the work is split along the line of what is *countable*:

    Scenario supplies the SURFACE  — assets/dice/raw/face-src.png, one blank face in the
                                     board's style, generated by the same flux + LoRA pair
                                     the tiles use, so the die matches the board.
    This tool supplies the COUNTS  — the six pip layouts, where they sit, which value lands
                                     on which face, and the geometry underneath.

The result is verified from the pixels, not from the table that drew them: --check re-reads the
finished atlas, counts blobs per face, and fails if any face doesn't hold the pips it claims.

Zero dependencies, like tools/normalize-env.py — PNG in and out through zlib.

    python3 tools/make-dice.py                    # build from the default paths
    python3 tools/make-dice.py --check            # build, then verify the atlas by counting pips
"""

import argparse
import math
import os
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

# ---------------------------------------------------------------------------------------------
# The die itself
# ---------------------------------------------------------------------------------------------
# Faces, in the order the engine's axes run: +X right, +Y up, +Z toward the viewer.
#
# The values are not a free choice. A Western die is right-handed: with 1 up and 2 facing you,
# 3 is on the RIGHT. Combined with opposite-faces-sum-to-7 that fixes all six at once, and the
# --check pass asserts both rules rather than trusting this table.
#
#   axis      value   right (u+)      up (v+)
FACES = [
    ("+X",  3, (0, 0, -1), (0, 1, 0)),
    ("-X",  4, (0, 0,  1), (0, 1, 0)),
    ("+Y",  1, (1, 0,  0), (0, 0, -1)),
    ("-Y",  6, (1, 0,  0), (0, 0,  1)),
    ("+Z",  2, (1, 0,  0), (0, 1, 0)),
    ("-Z",  5, (-1, 0, 0), (0, 1, 0)),
]

# Pip positions on a 3x3 grid, column-major cell ids:
#   0 1 2
#   3 4 5
#   6 7 8
PIPS = {
    1: [4],
    2: [0, 8],
    3: [0, 4, 8],
    4: [0, 2, 6, 8],
    5: [0, 2, 4, 6, 8],
    6: [0, 2, 3, 5, 6, 8],
}


# ---------------------------------------------------------------------------------------------
# PNG, both directions. Only what this tool actually meets: 8-bit, non-interlaced, grey/RGB/RGBA.
# ---------------------------------------------------------------------------------------------
def png_read(path):
    """-> (w, h, bytearray of RGB triples)."""
    data = open(path, "rb").read()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        sys.exit(f"{path}: not a PNG")
    pos, idat, w, h, ct = 8, [], None, None, None
    while pos + 8 <= len(data):
        ln = int.from_bytes(data[pos:pos + 4], "big")
        typ = data[pos + 4:pos + 8]
        chunk = data[pos + 8:pos + 8 + ln]
        pos += 12 + ln
        if typ == b"IHDR":
            w, h, bd, ct, _comp, _filt, inter = struct.unpack(">IIBBBBB", chunk)
            if bd != 8 or inter or ct not in (0, 2, 6):
                sys.exit(f"{path}: need an 8-bit non-interlaced grey/RGB/RGBA PNG "
                         f"(got bit depth {bd}, colour type {ct}, interlace {inter})")
        elif typ == b"IDAT":
            idat.append(chunk)
        elif typ == b"IEND":
            break
    raw = zlib.decompress(b"".join(idat))

    nch = {0: 1, 2: 3, 6: 4}[ct]
    stride = w * nch
    prev = bytearray(stride)
    rgb = bytearray(w * h * 3)
    p = 0
    for y in range(h):
        f = raw[p]; p += 1
        line = bytearray(raw[p:p + stride]); p += stride
        if f == 1:
            for i in range(nch, stride):
                line[i] = (line[i] + line[i - nch]) & 255
        elif f == 2:
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 255
        elif f == 3:
            for i in range(stride):
                a = line[i - nch] if i >= nch else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 255
        elif f == 4:
            for i in range(stride):
                a = line[i - nch] if i >= nch else 0
                c = prev[i - nch] if i >= nch else 0
                b = prev[i]
                est = a + b - c
                da, db, dc = abs(est - a), abs(est - b), abs(est - c)
                pred = a if (da <= db and da <= dc) else (b if db <= dc else c)
                line[i] = (line[i] + pred) & 255
        elif f != 0:
            sys.exit(f"{path}: unknown scanline filter {f}")
        o = y * w * 3
        if nch == 3:
            rgb[o:o + w * 3] = line
        elif nch == 1:
            for x in range(w):
                rgb[o + x * 3] = rgb[o + x * 3 + 1] = rgb[o + x * 3 + 2] = line[x]
        else:
            for x in range(w):
                rgb[o + x * 3:o + x * 3 + 3] = line[x * 4:x * 4 + 3]
        prev = line
    return w, h, rgb


def png_write(path, w, h, rgb):
    raw = bytearray()
    for y in range(h):
        raw.append(0)                                  # filter 0; the atlas compresses fine flat
        raw += rgb[y * w * 3:(y + 1) * w * 3]

    def chunk(typ, payload):
        return (struct.pack(">I", len(payload)) + typ + payload
                + struct.pack(">I", zlib.crc32(typ + payload) & 0xFFFFFFFF))

    blob = (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0))
            + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
            + chunk(b"IEND", b""))
    open(path, "wb").write(blob)
    return blob


# ---------------------------------------------------------------------------------------------
# Image helpers
# ---------------------------------------------------------------------------------------------
def crop_resize(w, h, rgb, box, size):
    """Crop `box` (fractions of the source) and bilinear-resample it to size x size."""
    x0, y0, x1, y1 = (box[0] * w, box[1] * h, box[2] * w, box[3] * h)
    out = bytearray(size * size * 3)
    for j in range(size):
        sy = y0 + (y1 - y0) * (j + 0.5) / size - 0.5
        j0 = max(0, min(h - 1, int(math.floor(sy)))); j1 = min(h - 1, j0 + 1)
        fy = max(0.0, min(1.0, sy - j0))
        for i in range(size):
            sx = x0 + (x1 - x0) * (i + 0.5) / size - 0.5
            i0 = max(0, min(w - 1, int(math.floor(sx)))); i1 = min(w - 1, i0 + 1)
            fx = max(0.0, min(1.0, sx - i0))
            o = (j * size + i) * 3
            for c in range(3):
                a = rgb[(j0 * w + i0) * 3 + c] * (1 - fx) + rgb[(j0 * w + i1) * 3 + c] * fx
                b = rgb[(j1 * w + i0) * 3 + c] * (1 - fx) + rgb[(j1 * w + i1) * 3 + c] * fx
                out[o + c] = int(a * (1 - fy) + b * fy + 0.5)
    return out


def rotate90(size, img, turns):
    """Rotate a square image by `turns` quarter-turns, so six faces cut from one swatch
    don't read as six photocopies of the same grain."""
    turns %= 4
    if turns == 0:
        return bytearray(img)
    out = bytearray(len(img))
    for y in range(size):
        for x in range(size):
            if turns == 1:
                sx, sy = y, size - 1 - x
            elif turns == 2:
                sx, sy = size - 1 - x, size - 1 - y
            else:
                sx, sy = size - 1 - y, x
            d, s = (y * size + x) * 3, (sy * size + sx) * 3
            out[d:d + 3] = img[s:s + 3]
    return out


def median_rgb(size, img):
    ch = []
    for c in range(3):
        vals = sorted(img[c::3])
        ch.append(vals[len(vals) // 2])
    return tuple(ch)


def stamp_pip(size, img, cx, cy, r, dark):
    """A pip, drawn as a recess rather than a sticker: the disc is darkened, its upper-left rim
    darker still and its lower-right rim lifted, which is what sells a carved dot under the
    board's single soft key light. Coverage is analytic, so the edge is clean at any radius."""
    x0, x1 = max(0, int(cx - r - 2)), min(size - 1, int(cx + r + 2))
    y0, y1 = max(0, int(cy - r - 2)), min(size - 1, int(cy + r + 2))
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            dx, dy = x + 0.5 - cx, y + 0.5 - cy
            d = math.hypot(dx, dy)
            cov = max(0.0, min(1.0, (r - d) + 0.5))     # 1px analytic feather
            if cov <= 0:
                continue
            # -1 at the upper-left rim, +1 at the lower-right; 0 across the flat middle
            rim = max(0.0, (d / r) - 0.55) / 0.45
            lean = (dx + dy) / (r * 1.4142) * rim
            shade = 1.0 + 0.45 * lean
            o = (y * size + x) * 3
            for c in range(3):
                tgt = max(0, min(255, int(dark[c] * shade)))
                img[o + c] = int(img[o + c] * (1 - cov) + tgt * cov + 0.5)


def build_atlas(face, cell, pip_r, pip_gap, dark):
    """Six faces into a 3x2 atlas. Value v occupies cell v-1, left to right, top to bottom."""
    aw, ah = cell * 3, cell * 2
    atlas = bytearray(aw * ah * 3)
    for name, value, _r, _u in FACES:
        base = rotate90(cell, face, value - 1)
        step = cell * pip_gap
        mid = cell / 2.0
        for slot in PIPS[value]:
            cx = mid + (slot % 3 - 1) * step
            cy = mid + (slot // 3 - 1) * step
            stamp_pip(cell, base, cx, cy, cell * pip_r, dark)
        col, row = (value - 1) % 3, (value - 1) // 3
        for y in range(cell):
            d = ((row * cell + y) * aw + col * cell) * 3
            atlas[d:d + cell * 3] = base[y * cell * 3:(y + 1) * cell * 3]
    return aw, ah, atlas


# ---------------------------------------------------------------------------------------------
# Geometry: a rounded cube, one grid per face
# ---------------------------------------------------------------------------------------------
def rounded_box(half, radius, seg):
    """Positions, normals, UVs and indices for a rounded cube of half-extent `half`.

    The roundover comes from the standard clamp identity: for a point p on the cube, take
    c = clamp(p, -(half-radius), +(half-radius)) and push it back out by the radius along
    p-c. Two useful things fall out of it for free. Adjacent faces land on exactly the same
    positions and normals along their shared bevel, so the cube is watertight and shades
    smoothly without any welding; and each face keeps its own planar UV, so a pip painted
    at the centre of a face texture arrives at the centre of a flat face, never smeared
    around a corner. The bevel eats only the outer border of each cell, which is bare
    material by construction.
    """
    pos, nrm, uv, idx = [], [], [], []
    inner = half - radius
    for _name, value, r, u in FACES:
        n = (r[1] * u[2] - r[2] * u[1], r[2] * u[0] - r[0] * u[2], r[0] * u[1] - r[1] * u[0])
        col, row = (value - 1) % 3, (value - 1) // 3
        first = len(pos)
        for j in range(seg + 1):
            t = -1.0 + 2.0 * j / seg
            for i in range(seg + 1):
                s = -1.0 + 2.0 * i / seg
                p = [n[k] * half + r[k] * s * half + u[k] * t * half for k in range(3)]
                c = [max(-inner, min(inner, v)) for v in p]
                d = [p[k] - c[k] for k in range(3)]
                ln = math.sqrt(sum(v * v for v in d)) or 1.0
                d = [v / ln for v in d]
                pos.append(tuple(c[k] + d[k] * radius for k in range(3)))
                nrm.append(tuple(d))
                # glTF UV origin is top-left, so v runs down: t=+1 is the top of the cell.
                fu, fv = (s + 1.0) / 2.0, (1.0 - t) / 2.0
                uv.append(((col + fu) / 3.0, (row + fv) / 2.0))
        for j in range(seg):
            for i in range(seg):
                a = first + j * (seg + 1) + i
                b, cc, dd = a + 1, a + seg + 2, a + seg + 1
                idx += [a, b, cc, a, cc, dd]      # CCW from outside: (r, u, n) is right-handed
    return pos, nrm, uv, idx


# ---------------------------------------------------------------------------------------------
# GLB
# ---------------------------------------------------------------------------------------------
def write_glb(path, pos, nrm, uv, idx, png):
    import json

    def pad(b):
        return b + b"\x00" * ((4 - len(b) % 4) % 4)

    b_pos = struct.pack(f"<{len(pos) * 3}f", *[c for v in pos for c in v])
    b_nrm = struct.pack(f"<{len(nrm) * 3}f", *[c for v in nrm for c in v])
    b_uv = struct.pack(f"<{len(uv) * 2}f", *[c for v in uv for c in v])
    b_idx = struct.pack(f"<{len(idx)}H", *idx)

    blobs, views, off = [b_pos, b_nrm, b_uv, b_idx, png], [], 0
    for i, b in enumerate(blobs):
        views.append({"buffer": 0, "byteOffset": off, "byteLength": len(b)})
        if i < 4:
            views[-1]["target"] = 34963 if i == 3 else 34962
        off += len(pad(b))
    bin_chunk = b"".join(pad(b) for b in blobs)

    lo = [min(v[k] for v in pos) for k in range(3)]
    hi = [max(v[k] for v in pos) for k in range(3)]
    gltf = {
        "asset": {"version": "2.0", "generator": "tools/make-dice.py"},
        "scene": 0,
        "scenes": [{"nodes": [0]}],
        "nodes": [{"mesh": 0, "name": "die"}],
        "meshes": [{"name": "die", "primitives": [
            {"attributes": {"POSITION": 0, "NORMAL": 1, "TEXCOORD_0": 2},
             "indices": 3, "material": 0}]}],
        "accessors": [
            {"bufferView": 0, "componentType": 5126, "count": len(pos), "type": "VEC3",
             "min": lo, "max": hi},
            {"bufferView": 1, "componentType": 5126, "count": len(nrm), "type": "VEC3"},
            {"bufferView": 2, "componentType": 5126, "count": len(uv), "type": "VEC2"},
            {"bufferView": 3, "componentType": 5123, "count": len(idx), "type": "SCALAR"},
        ],
        "bufferViews": views,
        "buffers": [{"byteLength": len(bin_chunk)}],
        "materials": [{"name": "die", "pbrMetallicRoughness": {
            "baseColorTexture": {"index": 0}, "metallicFactor": 0.0, "roughnessFactor": 0.85}}],
        "textures": [{"source": 0, "sampler": 0}],
        "images": [{"bufferView": 4, "mimeType": "image/png"}],
        # CLAMP_TO_EDGE on both axes: the atlas packs six faces, so a wrapping sampler would
        # bleed one face's border into the next at the bevel.
        "samplers": [{"magFilter": 9729, "minFilter": 9987, "wrapS": 33071, "wrapT": 33071}],
    }
    js = pad(json.dumps(gltf, separators=(",", ":")).encode("utf-8")).replace(b"\x00", b" ")
    out = (struct.pack("<III", 0x46546C67, 2, 12 + 8 + len(js) + 8 + len(bin_chunk))
           + struct.pack("<II", len(js), 0x4E4F534A) + js
           + struct.pack("<II", len(bin_chunk), 0x004E4942) + bin_chunk)
    open(path, "wb").write(out)
    return len(out)


# ---------------------------------------------------------------------------------------------
# Verification — counted off the finished pixels, not off the table that drew them
# ---------------------------------------------------------------------------------------------
def count_pips(aw, ah, atlas, cell, light):
    """Flood-fill the dark blobs in each atlas cell. Deliberately independent of PIPS: this is
    what turns 'the layout table says 6' into 'the texture holds six dots'."""
    found = {}
    for value in range(1, 7):
        col, row = (value - 1) % 3, (value - 1) // 3
        ox, oy = col * cell, row * cell
        thr = (light[0] + light[1] + light[2]) / 3.0 * 0.72
        mask = bytearray(cell * cell)
        for y in range(cell):
            for x in range(cell):
                o = ((oy + y) * aw + ox + x) * 3
                lum = (atlas[o] + atlas[o + 1] + atlas[o + 2]) / 3.0
                mask[y * cell + x] = 1 if lum < thr else 0
        blobs, seen = 0, bytearray(cell * cell)
        for y in range(cell):
            for x in range(cell):
                if not mask[y * cell + x] or seen[y * cell + x]:
                    continue
                stack, area = [(x, y)], 0
                seen[y * cell + x] = 1
                while stack:
                    px, py = stack.pop()
                    area += 1
                    for nx, ny in ((px + 1, py), (px - 1, py), (px, py + 1), (px, py - 1)):
                        if 0 <= nx < cell and 0 <= ny < cell and mask[ny * cell + nx] \
                                and not seen[ny * cell + nx]:
                            seen[ny * cell + nx] = 1
                            stack.append((nx, ny))
                if area > (cell * 0.02) ** 2:           # ignore grain speckle in the wood
                    blobs += 1
        found[value] = blobs
    return found


def verify_glb(path, cell):
    """Re-open the finished GLB and prove the mapping from its own bytes.

    The atlas check above only says the texture holds the right dots. This says the right dot
    lands on the right face, which is the part a layout table cannot promise: it walks the
    POSITION/TEXCOORD accessors, finds the vertex sitting dead centre of each face, follows its
    UV into the atlas cell it actually samples, and counts the pips in that cell from the PNG
    embedded in the file. Winding is checked at the same time — a face wound inside-out is
    invisible from the front and would otherwise ship.
    """
    import json

    blob = open(path, "rb").read()
    _magic, _ver, _ln = struct.unpack("<III", blob[:12])
    pos = 12
    js = bin_ = None
    while pos < len(blob):
        clen, ctype = struct.unpack("<II", blob[pos:pos + 8])
        body = blob[pos + 8:pos + 8 + clen]
        pos += 8 + clen
        if ctype == 0x4E4F534A:
            js = json.loads(body.decode("utf-8"))
        elif ctype == 0x004E4942:
            bin_ = body
    g = js

    def view(i):
        v = g["bufferViews"][i]
        off = v.get("byteOffset", 0)
        return bin_[off:off + v["byteLength"]]

    def acc(i, fmt, n):
        a = g["accessors"][i]
        raw = view(a["bufferView"])
        return [struct.unpack_from(f"<{n}{fmt}", raw, k * n * (4 if fmt == "f" else 2))
                for k in range(a["count"])]

    prim = g["meshes"][0]["primitives"][0]
    P = acc(prim["attributes"]["POSITION"], "f", 3)
    UV = acc(prim["attributes"]["TEXCOORD_0"], "f", 2)
    idx = [v[0] for v in acc(prim["indices"], "H", 1)]

    png = view(g["images"][0]["bufferView"])
    tmp = path + ".verify.png"
    open(tmp, "wb").write(png)
    try:
        aw, ah, atlas = png_read(tmp)
    finally:
        os.remove(tmp)
    counted = count_pips(aw, ah, atlas, cell, median_rgb_flat(aw, ah, atlas))

    rows, bad = [], 0
    for name, value, _r, _u in FACES:
        axis = "XYZ".index(name[1])
        sgn = 1.0 if name[0] == "+" else -1.0
        target = [0.0, 0.0, 0.0]
        target[axis] = sgn * 0.5
        k = min(range(len(P)), key=lambda i: sum((P[i][c] - target[c]) ** 2 for c in range(3)))
        u, v = UV[k]
        col, row = int(u * 3), int(v * 2)
        cellv = row * 3 + col + 1                    # which value that cell holds
        got = counted.get(cellv, -1)
        ok = cellv == value and got == len(PIPS[value])

        # winding: the first triangle touching this face's centre vertex must face outward
        wind = "?"
        for t in range(0, len(idx), 3):
            if k in idx[t:t + 3]:
                a, b, c = (P[idx[t]], P[idx[t + 1]], P[idx[t + 2]])
                e1 = [b[i] - a[i] for i in range(3)]
                e2 = [c[i] - a[i] for i in range(3)]
                cr = [e1[1] * e2[2] - e1[2] * e2[1],
                      e1[2] * e2[0] - e1[0] * e2[2],
                      e1[0] * e2[1] - e1[1] * e2[0]]
                wind = "out" if cr[axis] * sgn > 0 else "IN"
                break
        ok = ok and wind == "out"
        bad += not ok
        rows.append((name, value, cellv, got, wind, ok))
    return rows, bad


def median_rgb_flat(w, h, rgb):
    ch = []
    for c in range(3):
        vals = sorted(rgb[c::3])
        ch.append(vals[len(vals) // 2])
    return tuple(ch)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default=os.path.join(REPO, "assets/dice/raw/face-src.png"),
                    help="blank die face from Scenario")
    ap.add_argument("--out", default=os.path.join(REPO, "assets/dice/models/die.glb"))
    ap.add_argument("--atlas", default=os.path.join(REPO, "assets/dice/raw/atlas.png"),
                    help="the baked atlas, also written out so it can be eyeballed")
    # The generated face is a modelled block, not a flat swatch: it has a bevelled border, a
    # rounded inner corner and a drop shadow down its right and bottom. A square crop that
    # reaches into any of those brings a dark wedge along, which then reads as a seventh pip —
    # which is exactly how --check first caught this. 0.25 is the widest crop with nothing
    # below the pip threshold anywhere inside it, and at a 512 cell it is also 1:1.
    ap.add_argument("--crop", default="0.25,0.25,0.75,0.75",
                    help="x0,y0,x1,y1 as fractions — the flat interior of the source face")
    ap.add_argument("--cell", type=int, default=512, help="pixels per face")
    ap.add_argument("--pip-radius", type=float, default=0.072, help="fraction of the face")
    ap.add_argument("--pip-gap", type=float, default=0.25, help="pip grid spacing, ditto")
    ap.add_argument("--radius", type=float, default=0.10, help="corner roundover, unit cube")
    ap.add_argument("--seg", type=int, default=8, help="grid segments per face side")
    ap.add_argument("--check", action="store_true", help="re-count the pips from the atlas")
    a = ap.parse_args()

    # The die convention, asserted rather than assumed.
    by_axis = {name: v for name, v, _r, _u in FACES}
    for x, y in (("+X", "-X"), ("+Y", "-Y"), ("+Z", "-Z")):
        if by_axis[x] + by_axis[y] != 7:
            sys.exit(f"FACES: {x}={by_axis[x]} and {y}={by_axis[y]} do not sum to 7")
    if (by_axis["+Y"], by_axis["+Z"], by_axis["+X"]) != (1, 2, 3):
        sys.exit("FACES: not right-handed — 1 up and 2 front must put 3 on the right")

    box = tuple(float(v) for v in a.crop.split(","))
    w, h, rgb = png_read(a.src)
    face = crop_resize(w, h, rgb, box, a.cell)
    light = median_rgb(a.cell, face)
    dark = tuple(int(c * 0.30) for c in light)      # keeps the material's hue, drops the value
    print(f"source  {os.path.relpath(a.src, REPO)}  {w}x{h}")
    print(f"face    #{light[0]:02X}{light[1]:02X}{light[2]:02X} "
          f"→ pips #{dark[0]:02X}{dark[1]:02X}{dark[2]:02X}")

    aw, ah, atlas = build_atlas(face, a.cell, a.pip_radius, a.pip_gap, dark)
    os.makedirs(os.path.dirname(a.atlas), exist_ok=True)
    png = png_write(a.atlas, aw, ah, atlas)
    print(f"atlas   {os.path.relpath(a.atlas, REPO)}  {aw}x{ah}  {len(png) / 1024:.0f} KB")

    pos, nrm, uv, idx = rounded_box(0.5, a.radius, a.seg)
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    size = write_glb(a.out, pos, nrm, uv, idx, png)
    print(f"mesh    {len(pos)} verts, {len(idx) // 3} tris, unit cube centred on the origin")
    print(f"glb     {os.path.relpath(a.out, REPO)}  {size / 1024:.0f} KB")

    print()
    print("        face  value  pips" + ("  counted" if a.check else ""))
    counted = count_pips(aw, ah, atlas, a.cell, light) if a.check else {}
    bad = 0
    for name, value, _r, _u in FACES:
        line = f"        {name:>4}  {value:>5}  {len(PIPS[value]):>4}"
        if a.check:
            got = counted[value]
            ok = got == len(PIPS[value])
            bad += not ok
            line += f"  {got:>7} {'ok' if ok else 'WRONG'}"
        print(line)
    if a.check and bad:
        sys.exit(f"\n{bad} face(s) do not carry the pips they should")

    if a.check:
        rows, gbad = verify_glb(a.out, a.cell)
        print()
        print("        the shipped GLB, read back:")
        print("        face  wants  samples cell  pips  winding")
        for name, value, cellv, got, wind, ok in rows:
            print(f"        {name:>4}  {value:>5}  {cellv:>12}  {got:>4}  {wind:>7}"
                  f"  {'ok' if ok else 'WRONG'}")
        if gbad:
            sys.exit(f"\n{gbad} face(s) sample the wrong part of the atlas")
        print("\nall six faces verified — atlas pixels, UV mapping and winding")


if __name__ == "__main__":
    main()
